// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i rates_project/internal/rates.ExchangeClient -o exchange_client_mock.go -n ExchangeClientMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ExchangeClientMock implements mm_rates.ExchangeClient
type ExchangeClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetRates          func(ctx context.Context) (fa1 []float64, fa2 []float64, err error)
	funcGetRatesOrigin    string
	inspectFuncGetRates   func(ctx context.Context)
	afterGetRatesCounter  uint64
	beforeGetRatesCounter uint64
	GetRatesMock          mExchangeClientMockGetRates
}

// NewExchangeClientMock returns a mock for mm_rates.ExchangeClient
func NewExchangeClientMock(t minimock.Tester) *ExchangeClientMock {
	m := &ExchangeClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetRatesMock = mExchangeClientMockGetRates{mock: m}
	m.GetRatesMock.callArgs = []*ExchangeClientMockGetRatesParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mExchangeClientMockGetRates struct {
	optional           bool
	mock               *ExchangeClientMock
	defaultExpectation *ExchangeClientMockGetRatesExpectation
	expectations       []*ExchangeClientMockGetRatesExpectation

	callArgs []*ExchangeClientMockGetRatesParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ExchangeClientMockGetRatesExpectation specifies expectation struct of the ExchangeClient.GetRates
type ExchangeClientMockGetRatesExpectation struct {
	mock               *ExchangeClientMock
	params             *ExchangeClientMockGetRatesParams
	paramPtrs          *ExchangeClientMockGetRatesParamPtrs
	expectationOrigins ExchangeClientMockGetRatesExpectationOrigins
	results            *ExchangeClientMockGetRatesResults
	returnOrigin       string
	Counter            uint64
}

// ExchangeClientMockGetRatesParams contains parameters of the ExchangeClient.GetRates
type ExchangeClientMockGetRatesParams struct {
	ctx context.Context
}

// ExchangeClientMockGetRatesParamPtrs contains pointers to parameters of the ExchangeClient.GetRates
type ExchangeClientMockGetRatesParamPtrs struct {
	ctx *context.Context
}

// ExchangeClientMockGetRatesResults contains results of the ExchangeClient.GetRates
type ExchangeClientMockGetRatesResults struct {
	fa1 []float64
	fa2 []float64
	err error
}

// ExchangeClientMockGetRatesOrigins contains origins of expectations of the ExchangeClient.GetRates
type ExchangeClientMockGetRatesExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetRates *mExchangeClientMockGetRates) Optional() *mExchangeClientMockGetRates {
	mmGetRates.optional = true
	return mmGetRates
}

// Expect sets up expected params for ExchangeClient.GetRates
func (mmGetRates *mExchangeClientMockGetRates) Expect(ctx context.Context) *mExchangeClientMockGetRates {
	if mmGetRates.mock.funcGetRates != nil {
		mmGetRates.mock.t.Fatalf("ExchangeClientMock.GetRates mock is already set by Set")
	}

	if mmGetRates.defaultExpectation == nil {
		mmGetRates.defaultExpectation = &ExchangeClientMockGetRatesExpectation{}
	}

	if mmGetRates.defaultExpectation.paramPtrs != nil {
		mmGetRates.mock.t.Fatalf("ExchangeClientMock.GetRates mock is already set by ExpectParams functions")
	}

	mmGetRates.defaultExpectation.params = &ExchangeClientMockGetRatesParams{ctx}
	mmGetRates.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetRates.expectations {
		if minimock.Equal(e.params, mmGetRates.defaultExpectation.params) {
			mmGetRates.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetRates.defaultExpectation.params)
		}
	}

	return mmGetRates
}

// ExpectCtxParam1 sets up expected param ctx for ExchangeClient.GetRates
func (mmGetRates *mExchangeClientMockGetRates) ExpectCtxParam1(ctx context.Context) *mExchangeClientMockGetRates {
	if mmGetRates.mock.funcGetRates != nil {
		mmGetRates.mock.t.Fatalf("ExchangeClientMock.GetRates mock is already set by Set")
	}

	if mmGetRates.defaultExpectation == nil {
		mmGetRates.defaultExpectation = &ExchangeClientMockGetRatesExpectation{}
	}

	if mmGetRates.defaultExpectation.params != nil {
		mmGetRates.mock.t.Fatalf("ExchangeClientMock.GetRates mock is already set by Expect")
	}

	if mmGetRates.defaultExpectation.paramPtrs == nil {
		mmGetRates.defaultExpectation.paramPtrs = &ExchangeClientMockGetRatesParamPtrs{}
	}
	mmGetRates.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetRates.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetRates
}

// Inspect accepts an inspector function that has same arguments as the ExchangeClient.GetRates
func (mmGetRates *mExchangeClientMockGetRates) Inspect(f func(ctx context.Context)) *mExchangeClientMockGetRates {
	if mmGetRates.mock.inspectFuncGetRates != nil {
		mmGetRates.mock.t.Fatalf("Inspect function is already set for ExchangeClientMock.GetRates")
	}

	mmGetRates.mock.inspectFuncGetRates = f

	return mmGetRates
}

// Return sets up results that will be returned by ExchangeClient.GetRates
func (mmGetRates *mExchangeClientMockGetRates) Return(fa1 []float64, fa2 []float64, err error) *ExchangeClientMock {
	if mmGetRates.mock.funcGetRates != nil {
		mmGetRates.mock.t.Fatalf("ExchangeClientMock.GetRates mock is already set by Set")
	}

	if mmGetRates.defaultExpectation == nil {
		mmGetRates.defaultExpectation = &ExchangeClientMockGetRatesExpectation{mock: mmGetRates.mock}
	}
	mmGetRates.defaultExpectation.results = &ExchangeClientMockGetRatesResults{fa1, fa2, err}
	mmGetRates.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetRates.mock
}

// Set uses given function f to mock the ExchangeClient.GetRates method
func (mmGetRates *mExchangeClientMockGetRates) Set(f func(ctx context.Context) (fa1 []float64, fa2 []float64, err error)) *ExchangeClientMock {
	if mmGetRates.defaultExpectation != nil {
		mmGetRates.mock.t.Fatalf("Default expectation is already set for the ExchangeClient.GetRates method")
	}

	if len(mmGetRates.expectations) > 0 {
		mmGetRates.mock.t.Fatalf("Some expectations are already set for the ExchangeClient.GetRates method")
	}

	mmGetRates.mock.funcGetRates = f
	mmGetRates.mock.funcGetRatesOrigin = minimock.CallerInfo(1)
	return mmGetRates.mock
}

// When sets expectation for the ExchangeClient.GetRates which will trigger the result defined by the following
// Then helper
func (mmGetRates *mExchangeClientMockGetRates) When(ctx context.Context) *ExchangeClientMockGetRatesExpectation {
	if mmGetRates.mock.funcGetRates != nil {
		mmGetRates.mock.t.Fatalf("ExchangeClientMock.GetRates mock is already set by Set")
	}

	expectation := &ExchangeClientMockGetRatesExpectation{
		mock:               mmGetRates.mock,
		params:             &ExchangeClientMockGetRatesParams{ctx},
		expectationOrigins: ExchangeClientMockGetRatesExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetRates.expectations = append(mmGetRates.expectations, expectation)
	return expectation
}

// Then sets up ExchangeClient.GetRates return parameters for the expectation previously defined by the When method
func (e *ExchangeClientMockGetRatesExpectation) Then(fa1 []float64, fa2 []float64, err error) *ExchangeClientMock {
	e.results = &ExchangeClientMockGetRatesResults{fa1, fa2, err}
	return e.mock
}

// Times sets number of times ExchangeClient.GetRates should be invoked
func (mmGetRates *mExchangeClientMockGetRates) Times(n uint64) *mExchangeClientMockGetRates {
	if n == 0 {
		mmGetRates.mock.t.Fatalf("Times of ExchangeClientMock.GetRates mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetRates.expectedInvocations, n)
	mmGetRates.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetRates
}

func (mmGetRates *mExchangeClientMockGetRates) invocationsDone() bool {
	if len(mmGetRates.expectations) == 0 && mmGetRates.defaultExpectation == nil && mmGetRates.mock.funcGetRates == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetRates.mock.afterGetRatesCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetRates.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetRates implements mm_rates.ExchangeClient
func (mmGetRates *ExchangeClientMock) GetRates(ctx context.Context) (fa1 []float64, fa2 []float64, err error) {
	mm_atomic.AddUint64(&mmGetRates.beforeGetRatesCounter, 1)
	defer mm_atomic.AddUint64(&mmGetRates.afterGetRatesCounter, 1)

	mmGetRates.t.Helper()

	if mmGetRates.inspectFuncGetRates != nil {
		mmGetRates.inspectFuncGetRates(ctx)
	}

	mm_params := ExchangeClientMockGetRatesParams{ctx}

	// Record call args
	mmGetRates.GetRatesMock.mutex.Lock()
	mmGetRates.GetRatesMock.callArgs = append(mmGetRates.GetRatesMock.callArgs, &mm_params)
	mmGetRates.GetRatesMock.mutex.Unlock()

	for _, e := range mmGetRates.GetRatesMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.fa1, e.results.fa2, e.results.err
		}
	}

	if mmGetRates.GetRatesMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetRates.GetRatesMock.defaultExpectation.Counter, 1)
		mm_want := mmGetRates.GetRatesMock.defaultExpectation.params
		mm_want_ptrs := mmGetRates.GetRatesMock.defaultExpectation.paramPtrs

		mm_got := ExchangeClientMockGetRatesParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetRates.t.Errorf("ExchangeClientMock.GetRates got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetRates.GetRatesMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetRates.t.Errorf("ExchangeClientMock.GetRates got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetRates.GetRatesMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetRates.GetRatesMock.defaultExpectation.results
		if mm_results == nil {
			mmGetRates.t.Fatal("No results are set for the ExchangeClientMock.GetRates")
		}
		return (*mm_results).fa1, (*mm_results).fa2, (*mm_results).err
	}
	if mmGetRates.funcGetRates != nil {
		return mmGetRates.funcGetRates(ctx)
	}
	mmGetRates.t.Fatalf("Unexpected call to ExchangeClientMock.GetRates. %v", ctx)
	return
}

// GetRatesAfterCounter returns a count of finished ExchangeClientMock.GetRates invocations
func (mmGetRates *ExchangeClientMock) GetRatesAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetRates.afterGetRatesCounter)
}

// GetRatesBeforeCounter returns a count of ExchangeClientMock.GetRates invocations
func (mmGetRates *ExchangeClientMock) GetRatesBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetRates.beforeGetRatesCounter)
}

// Calls returns a list of arguments used in each call to ExchangeClientMock.GetRates.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetRates *mExchangeClientMockGetRates) Calls() []*ExchangeClientMockGetRatesParams {
	mmGetRates.mutex.RLock()

	argCopy := make([]*ExchangeClientMockGetRatesParams, len(mmGetRates.callArgs))
	copy(argCopy, mmGetRates.callArgs)

	mmGetRates.mutex.RUnlock()

	return argCopy
}

// MinimockGetRatesDone returns true if the count of the GetRates invocations corresponds
// the number of defined expectations
func (m *ExchangeClientMock) MinimockGetRatesDone() bool {
	if m.GetRatesMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetRatesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetRatesMock.invocationsDone()
}

// MinimockGetRatesInspect logs each unmet expectation
func (m *ExchangeClientMock) MinimockGetRatesInspect() {
	for _, e := range m.GetRatesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ExchangeClientMock.GetRates at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetRatesCounter := mm_atomic.LoadUint64(&m.afterGetRatesCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetRatesMock.defaultExpectation != nil && afterGetRatesCounter < 1 {
		if m.GetRatesMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ExchangeClientMock.GetRates at\n%s", m.GetRatesMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ExchangeClientMock.GetRates at\n%s with params: %#v", m.GetRatesMock.defaultExpectation.expectationOrigins.origin, *m.GetRatesMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetRates != nil && afterGetRatesCounter < 1 {
		m.t.Errorf("Expected call to ExchangeClientMock.GetRates at\n%s", m.funcGetRatesOrigin)
	}

	if !m.GetRatesMock.invocationsDone() && afterGetRatesCounter > 0 {
		m.t.Errorf("Expected %d calls to ExchangeClientMock.GetRates at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetRatesMock.expectedInvocations), m.GetRatesMock.expectedInvocationsOrigin, afterGetRatesCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ExchangeClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetRatesInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ExchangeClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ExchangeClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetRatesDone()
}
