// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i rates_project/internal/rates.RateRepository -o rate_repository_mock.go -n RateRepositoryMock -p mocks

import (
	"context"
	"rates_project/internal/domain/models"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// RateRepositoryMock implements mm_rates.RateRepository
type RateRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, rate *models.Rate) (err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, rate *models.Rate)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mRateRepositoryMockCreate
}

// NewRateRepositoryMock returns a mock for mm_rates.RateRepository
func NewRateRepositoryMock(t minimock.Tester) *RateRepositoryMock {
	m := &RateRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mRateRepositoryMockCreate{mock: m}
	m.CreateMock.callArgs = []*RateRepositoryMockCreateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRateRepositoryMockCreate struct {
	optional           bool
	mock               *RateRepositoryMock
	defaultExpectation *RateRepositoryMockCreateExpectation
	expectations       []*RateRepositoryMockCreateExpectation

	callArgs []*RateRepositoryMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RateRepositoryMockCreateExpectation specifies expectation struct of the RateRepository.Create
type RateRepositoryMockCreateExpectation struct {
	mock               *RateRepositoryMock
	params             *RateRepositoryMockCreateParams
	paramPtrs          *RateRepositoryMockCreateParamPtrs
	expectationOrigins RateRepositoryMockCreateExpectationOrigins
	results            *RateRepositoryMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// RateRepositoryMockCreateParams contains parameters of the RateRepository.Create
type RateRepositoryMockCreateParams struct {
	ctx  context.Context
	rate *models.Rate
}

// RateRepositoryMockCreateParamPtrs contains pointers to parameters of the RateRepository.Create
type RateRepositoryMockCreateParamPtrs struct {
	ctx  *context.Context
	rate **models.Rate
}

// RateRepositoryMockCreateResults contains results of the RateRepository.Create
type RateRepositoryMockCreateResults struct {
	err error
}

// RateRepositoryMockCreateOrigins contains origins of expectations of the RateRepository.Create
type RateRepositoryMockCreateExpectationOrigins struct {
	origin     string
	originCtx  string
	originRate string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mRateRepositoryMockCreate) Optional() *mRateRepositoryMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for RateRepository.Create
func (mmCreate *mRateRepositoryMockCreate) Expect(ctx context.Context, rate *models.Rate) *mRateRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("RateRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &RateRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("RateRepositoryMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &RateRepositoryMockCreateParams{ctx, rate}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for RateRepository.Create
func (mmCreate *mRateRepositoryMockCreate) ExpectCtxParam1(ctx context.Context) *mRateRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("RateRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &RateRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("RateRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &RateRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectRateParam2 sets up expected param rate for RateRepository.Create
func (mmCreate *mRateRepositoryMockCreate) ExpectRateParam2(rate *models.Rate) *mRateRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("RateRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &RateRepositoryMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("RateRepositoryMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &RateRepositoryMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.rate = &rate
	mmCreate.defaultExpectation.expectationOrigins.originRate = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the RateRepository.Create
func (mmCreate *mRateRepositoryMockCreate) Inspect(f func(ctx context.Context, rate *models.Rate)) *mRateRepositoryMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for RateRepositoryMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by RateRepository.Create
func (mmCreate *mRateRepositoryMockCreate) Return(err error) *RateRepositoryMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("RateRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &RateRepositoryMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &RateRepositoryMockCreateResults{err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the RateRepository.Create method
func (mmCreate *mRateRepositoryMockCreate) Set(f func(ctx context.Context, rate *models.Rate) (err error)) *RateRepositoryMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the RateRepository.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the RateRepository.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the RateRepository.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mRateRepositoryMockCreate) When(ctx context.Context, rate *models.Rate) *RateRepositoryMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("RateRepositoryMock.Create mock is already set by Set")
	}

	expectation := &RateRepositoryMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &RateRepositoryMockCreateParams{ctx, rate},
		expectationOrigins: RateRepositoryMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up RateRepository.Create return parameters for the expectation previously defined by the When method
func (e *RateRepositoryMockCreateExpectation) Then(err error) *RateRepositoryMock {
	e.results = &RateRepositoryMockCreateResults{err}
	return e.mock
}

// Times sets number of times RateRepository.Create should be invoked
func (mmCreate *mRateRepositoryMockCreate) Times(n uint64) *mRateRepositoryMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of RateRepositoryMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mRateRepositoryMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_rates.RateRepository
func (mmCreate *RateRepositoryMock) Create(ctx context.Context, rate *models.Rate) (err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, rate)
	}

	mm_params := RateRepositoryMockCreateParams{ctx, rate}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := RateRepositoryMockCreateParams{ctx, rate}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("RateRepositoryMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.rate != nil && !minimock.Equal(*mm_want_ptrs.rate, mm_got.rate) {
				mmCreate.t.Errorf("RateRepositoryMock.Create got unexpected parameter rate, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originRate, *mm_want_ptrs.rate, mm_got.rate, minimock.Diff(*mm_want_ptrs.rate, mm_got.rate))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("RateRepositoryMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the RateRepositoryMock.Create")
		}
		return (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, rate)
	}
	mmCreate.t.Fatalf("Unexpected call to RateRepositoryMock.Create. %v %v", ctx, rate)
	return
}

// CreateAfterCounter returns a count of finished RateRepositoryMock.Create invocations
func (mmCreate *RateRepositoryMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of RateRepositoryMock.Create invocations
func (mmCreate *RateRepositoryMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to RateRepositoryMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mRateRepositoryMockCreate) Calls() []*RateRepositoryMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*RateRepositoryMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *RateRepositoryMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *RateRepositoryMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RateRepositoryMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RateRepositoryMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RateRepositoryMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to RateRepositoryMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to RateRepositoryMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RateRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RateRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RateRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone()
}
